### ISSUE TITLE
Internal: rename rolling block

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#1051]
The name "rolling block" is taken from the OG and refers to the movable columns in Qualopec. This naming creates confusion even among the development team, and as such, it should be changed to something else. I propose to name it "movable pillar".

**Comment by walkawayy** [comment]
I was considering a name other than `movable pillar` because it's not movable like a normal block. It's more triggered. Not a huge deal. But I was looking at TRView and they call it `moving block`. What do you think about that name?

![image](https://github.com/LostArtefacts/TR1X/assets/81546780/75c1e336-9fcf-40ca-911b-def4680b09d8)

**Comment by rr-** [comment]
I think it's still confusing and reminds of pushables. What if we call it sliding pillar, sliding column or (least preferred) sliding block?

**Comment by walkawayy** [comment]
Sliding pillar sounds good to me.
