### ISSUE TITLE
Stacked portable buildings in Natla's Mines (Game breaking bug)

### ISSUE THREAD

**Issue by HyperSonic1999** [LostArtefacts/TRX#1052]
First time playing the game and ran into this game breaking bug where after putting in the third fuse, the cutscene doesn't play and the portable buildings duplicate with the one on top being blackened and because of this I was unable to progress any further. I thankfully had a save at the beginning of the level and ran though it again and this time I didn't get stuck.

I did two things differently on my second go, I got the Conveyor belt fuse second, instead last and I put in all the fuses at the same time, instead of whenever I got one.

Here's my saves with a readme file. They were created on v2.15.3, I then updated to v2.16 and got the same result.
[saves.zip](https://github.com/LostArtefacts/TR1X/files/12884162/saves.zip)

![Screenshot 2023-10-12 233852](https://github.com/LostArtefacts/TR1X/assets/77837137/0b0fe795-5279-4d14-a6d3-e03fc2b7c151)

**Comment by lahm86** [comment]
This is flipmap related and can happen if you do things in a certain order. It's a level design issue ultimately.

Did you happen to pull the lever below before collecting all fuses, and then return to the conveyor belt area? If you do this, the cabin will appear on the floor. It's because when the cabin lands normally, the engine triggers the flipmap, but that switch beyond the cowboy triggers the same flipmap index. When the cabin area is flipped, the fuse triggers aren't present, which is why you weren't able to lower it any further.

The issue is the design of the level suggests you should not pull that lever before finishing the cabin area (so that you have guns to kill the cowboy) but ultimately there is nothing to stop you from doing this.

I'm not sure if this is easily fixable. Flipmap issues like this are plentiful in the classic games - Aldwych in TR3 is probably the most notorious example.

![image](https://github.com/LostArtefacts/TR1X/assets/33758420/2a53b2ed-ab9e-4ca2-a9b1-9cfa7af9ead8)

![image](https://github.com/LostArtefacts/TR1X/assets/33758420/0e62bb72-55ac-4cd6-90a6-954ececee44e)

![image](https://github.com/LostArtefacts/TR1X/assets/33758420/255d27c4-420d-40ad-80b2-fb5b67aafddd)

**Comment by HyperSonic1999** [comment]
I believe I did things in this order. Went through the pathway where the minecart moved, moved the block backwards (was being enemy aware) and ended up glitched it into the drill of the minecart, missed the lever before the cowboy room, grabbed the fuse in the cowboy room, then went back to put it in.

Went back to the cowboy room and discovered platforms near the lava and dropped down, found the shotgun along the path, pulled the lever (Switch 30), then killed the cowboy with the shotgun and grabbed the magnums.

Put in the second fuse (I think I noticed some graphical bugs at this point), got stumped, then ended up watching a video guide and discovered the lever before the cowboy room, which let to the conveyor belt fuse, put the last fuse in and boom, stacked buildings. I did the same route on my second go as well, apart from getting the conveyor belt fuse before the cowboy fuse and putting all the fuses in at the end.

**Comment by aredfan** [comment]
Second bug related to this issue:

> I found a bug in Natla’s Mines that I don’t know if has been mentioned or is otherwise known. It’s been years since I’ve played the level and I couldn’t remember how to get the conveyor belt fuse so I passed cowboy and got the shotgun and pulled the TNT switch before getting that fuse. When I went back to the fuse, the conveyor belt was somehow on and the fuse was nowhere to be found. It had disappeared, leaving me with no way to get my pistols.
> 
> I was able to reload an earlier save and pull the proper switches and grab the conveyor belt fuse before fighting cowboy, but if I hadn’t made a backup save I wouldn’t have been able to get those pistols back.
> 
> [Source](https://www.tombraiderforums.com/showpost.php?p=8441486&postcount=243)

**Update:** Turns out this is more of a side-effect instead of a bug.  The switch near the conveyor still makes the fuse appear.

**Comment by Richard-L** [comment]
Fwiw, looks like this problem was reported here as well (thanks to Walkaway for pointing me here)

![](https://cdn.discordapp.com/attachments/951399533449977876/1212134473831813170/Screenshot_20240227-212800.png?ex=65f0bb32&is=65de4632&hm=410568b2035ca3978f23b388ea38c05811ea50fe489f125b86385e8c922ec2d0&)

**Comment by CharlesLove** [comment]
I recently got both the double building bug and related fuse issue as well. Luckily, just walking to the waterfall room and back fixed the floating building. From there I just walked into the fuse building and it properly dropped.
