### ISSUE TITLE
Restart Level passport page not visible when save crystals are enabled

### ISSUE THREAD

**Issue by pas-de-2** [LostArtefacts/TRX#1099]
I was going to ask about implementing the Restart Level feature from the PSX version, but I see now that it is available (on death), it's just not visible when save crystals are enabled.

While I'm here, I might as well also ask about the possibility of implementing the Restart Level page without having to die first.

**Comment by Richard-L** [comment]
Can't deny that I would still like this too.

We'd talked about it before: https://github.com/LostArtefacts/TR1X/issues/48

Iirc the problem was that an additional passport page would've been necessary. Wasn't sure why one couldn't be added (?).

**Comment by walkawayy** [comment]
I can work on supporting this. The save game page is the same page in the passport as restart level which is why it was disable for save crystal mode. Since the player can't save on demand. Seems like the logic was just not there to differentiate since save crystals and save anywhere are both options in TR1X.

**Comment by pas-de-2** [comment]
Thanks for addressing this. Since the second page goes unused with save crystals enabled while alive, could it be repurposed to show the restart level page instead, like in the PSX version?

**Comment by walkawayy** [comment]
Possibly. The passport code is a giant mess and a rewrite might be easier.
