### ISSUE TITLE
[3.0] Lara spawning without pistols in Feder's Oasis

### ISSUE THREAD

**Issue by pas-de-2** [LostArtefacts/TRX#1130]
https://www.trle.net/sc/levelfeatures.php?lid=3481

![20231225_110152_Caves](https://github.com/LostArtefacts/TR1X/assets/116680301/52e21202-37c9-44fc-8fbc-49954d0e6515)

Noticed Lara spawns in this TRLE without her pistols. She can draw them at first, but if you ever equip another weapon like a shotgun, you can't reselect the pistols.

Issue starts happening in TR1X version 3.0, in 2.16 the pistols load fine.

EDIT: tracked it down to commit https://github.com/LostArtefacts/TR1X/commit/56e1ae15229645972dc52349f01e079e627c84dc and the addition of this check in `Inv_AddItem`:

https://github.com/LostArtefacts/TR1X/blob/56e1ae15229645972dc52349f01e079e627c84dc/src/game/inventory/inventory_func.c#L14-L16

**Comment by walkawayy** [comment]
Can you share the TR1X gameflow script you made for this? Seems like this custom level was made with TombATI in mind.

**Comment by pas-de-2** [comment]
I used the normal TR1X gameflow, with caves_* injections removed.

**Comment by walkawayy** [comment]
Interesting it looks like the level file doesn't include the pistols sprite (object number 84) but it does include the 3D model (object number 99). Gonna tag @rr- since he added the change. I guess the sprite is only needed if the object can be picked up which usually doesn't apply to pistols. But it does happen in Natla's Mines or possibly customs levels. So, I lean on the side of it being a level error? But I'm not sure. But maybe we only need to check for the 3D object as `loaded` since Lara isn't picking it up in normal gameplay or in the case of the console.

![image](https://github.com/LostArtefacts/TR1X/assets/81546780/24390e32-83d2-48ff-b5a8-abf66b98ef59)

![image](https://github.com/LostArtefacts/TR1X/assets/81546780/c5606835-9a5a-418b-b782-2a53e70e6c84)
