### ISSUE TITLE
Black screen flickers when playing in 60 FPS

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#1192]
Doesn't seem to consistently happen at the same level geometry. Semi rare but still happens a decent amount.

Some video here:
https://github.com/LostArtefacts/TR1X/pull/1177#issuecomment-2016624323

#1177

**Comment by rr-** [comment]
@lahm86 @eikehein  do you think you can help with this one? My hunch is that the interpolated camera position needs to be sanitized so that it doesn't get stuck in a ceiling for example in-between frames, but actually this seems to happen most often around room portals – so maybe it's about rendering instead. It also happens in 30 FPS, just less often. One prominent location where this happens quite a lot is on the staircase in Lara's home.
