### ISSUE TITLE
Damocles swords turn speed

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1227]
I'm not sure if this is necessarily related to 60fps, but I noticed the swords in the Damocles room of folly, after having picked up the key, turn faster than on the PS1:

![image](https://github.com/LostArtefacts/TR1X/assets/4934209/02ac631c-1710-413c-9d0a-c1b818241d5f)

https://github.com/LostArtefacts/TR1X/assets/4934209/17b3668e-e4b5-48da-b41c-0f2444905ad8

PS1

https://github.com/LostArtefacts/TR1X/assets/4934209/01d95138-9c4a-458d-9612-4c29484f0253

https://github.com/LostArtefacts/TR1X/assets/4934209/fb856815-20a9-4920-b98c-bf49c4c75dcb

Also maybe a different issue (if it's interesting): When first entering this room, the caves ambient music track is triggered on the PS1. It alerts the player of something dangerous lingering because there is no wind ambient in the Greece levels on the PS1, and thus the game is perfectly silent until entering this room.
This track however does not seem to be triggered in TR1X.

**Comment by walkawayy** [comment]
I believe the speeds are randomized (`item->required_anim_state = (Random_GetControl() - 0x4000) / 16;`). You can see in your PS1 clip the speeds of all the swords are all different.

**Comment by walkawayy** [comment]
About the sound, idk if @lahm86 did any injection stuff since it's an ambient track. The trigger is definitely in the level file.

![image](https://github.com/LostArtefacts/TR1X/assets/81546780/b91be207-668f-441a-9ac5-aab7b0a423c9)

**Comment by Richard-L** [comment]
Thanks, that would explain both. Let's hear from Lahm, but would seem this can be closed. Unless we think using the caves ambient here does make sense? I'm not sure, and also just way too used to it playing in this spot.

**Comment by lahm86** [comment]
Track 5 is ignored by the game ([ref](https://github.com/LostArtefacts/TR1X/blob/develop/src/game/music.c#L29)). My understanding is that as there is no looped ambient mechanism in PS, these triggers were dotted around the levels instead, usually directly under Lara or otherwise part way through. TRR and TombATI also ignore these, not sure about DosBox.

I think they should remain ignored because the PC version has looped ambience. In Atlantis, for example, it would be jarring for the creepy heartbeat ambience to begin, then for Caves to kick in after Lara takes a few steps.

![image](https://github.com/LostArtefacts/TR1X/assets/33758420/48378292-4d5a-4e1d-b62b-05a6d1071293)

**Comment by Richard-L** [comment]
Good point.

There is another occasion I remembered in Obelisk, where you have to make your way up the green platforms after fighting the two panthers. Would probably be a bit odd to break the wind ambiance for caves.

Let's close this.
