### ISSUE TITLE
Wrong Lara rotation during UW twist

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#1242]
During the underwater roll/twist animation, Lara appears to be rotated at a random angle for a single frame in the second half of the animation.

@lahm86 can you please check? This is more evident with 60 fps and turbo=-2 in the latest develop.

**Comment by lahm86** [comment]
It's on OG bug in TR2 (and onwards I think) so TR1X has inherited it. We would need to edit the animation frames - I did try long ago but failed to get very far. I can take another look.

**Comment by rr-** [comment]
The issue seems to be gone when removing the calls to
```
    Matrix_RotYXZ(
        item->interp.result.rot.y, item->interp.result.rot.x,
        item->interp.result.rot.z);
```
in `lara_draw.c`.

**Comment by lahm86** [comment]
Documenting this here as it will need to be fixed in TR2X eventually.

- Remove flip effect 0 from the roll start animation and add it to the first frame of the roll end animation instead.
- Set yaw, pitch and roll on the first frame of the roll end animation to match the 20th frame of the roll start animation (the 20th is unused). Invert the pitch.
- Restore the defective anim command on the roll start animation for flip effect 3 - use frame 14.
- Ensure to link to frame 20 of the underwater idle animation from the roll end animation.
