### ISSUE TITLE
Key/Puzzle/Midas item item usage can be cancelled after selection due to inventory phase

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1254]
https://github.com/LostArtefacts/TR1X/assets/4934209/340bc3e3-a6fe-4538-a23b-751fcef41c2f

![image](https://github.com/LostArtefacts/TR1X/assets/4934209/839a57f4-97df-4309-80f1-fe219cdeada4)

**Comment by walkawayy** [comment]
@rr-  I believe this is due to the phaser change adding a one frame delay. In `KeyHole_Collision`, this runs:
```
    if (g_InvChosen == O_INVALID) {
        Inv_Display(INV_KEYS_MODE);
    } else {
        g_PickUpY = lara_item->pos.y - 1;
    }
```

but the inventory function no longer returns in place. Instead, the function is checked again from the start which means holding a direction can cause an early return because Lara can be in a different state if any input is held.
```
    if (lara_item->current_anim_state != LS_STOP) {
        return;
    }
```

Btw, this also can happen when the right key item is used. It's not a wrong key item only issue.

**Comment by walkawayy** [comment]
I looked at this a bunch tonight, and I wanted to rework `g_InvChosen` and `Inv_Close` entirely. But, I keep coming across gotchas like the inventory is a phaser which delays things a frame and also makes return values hard, you have to know which item number Lara is using in inventory, you can't call a `KeyHole_PutInKey` kind of function easily separate from the collision function, etc. I will try to keep thinking but if you have any ideas lmk.
