### ISSUE TITLE
Lara doesn't say "no" when using the Scion incorrectly

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#1278]

**Comment by walkawayy** [comment]
Lara also doesn't say no when using the Scion on keyholes or puzzle holes. We should probably have her say no in all cases.

**Comment by rr-** [comment]
Good catch, definitely agree

**Comment by walkawayy** [comment]
As far as I can tell, Lara will say "no" when using the wrong key items on the Midas hand, so I repurposed the issue to fix her "no"s when using the Scion. I think this is the last thing missing. I also tested using this custom level since the original Midas level has so few key items. https://trcustoms.org/levels/3596
