### ISSUE TITLE
TR1X bug: Demo 1 desync if fix bear AI enabled

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1370]
**Dev snapshot:** 4.1.2-26-g7351e7c

_____________________

At the end of the first demo when the bear attacks Lara, there is a small desync.  Left is 30 FPS, right is 60 FPS.  The desync only happens when playing in 60 FPS.

Video: https://drive.google.com/drive/folders/1wmzMAn9ARRajbLqT-yPeq5V_3-5S1T7v?usp=sharing

This is probably one of the trade-offs when using 60 FPS, if that's the case then please feel free to close the issue.

**Comment by Richard-L** [comment]
I've also had desyncs on both demos, but it was a bit tricky to work out if some of the new aiming modes from TR4 was the culprit.

I'd like to motivate auto-disabling any of these things for the demos only, also lean jumping and what not could mess with them, to keep them intact regardless of what the user has configured. 60fps though would be nice to maintain of course 😅

**Comment by aredfan** [comment]
Yep there was a bug with the new aiming modes affecting both demos, but that was fixed in #1179. 

I found the cause for this issue, demo mode 1 is affected by the  `Fix bear AI` option.

**Comment by Richard-L** [comment]
Oh excellent find!

**Comment by walkawayy** [comment]
Maybe it's worth adding in those config presets (#653). Then we could have a `Demo TR1` preset or something like that which gets updated if new config options are added. Then demo mode could load / unload the preset OG config instead of hard coding and restoring specific options in the demo code. I guess only certain options affect demo mode though and the user might want to display their custom bar colors and the like.

**Comment by Richard-L** [comment]
Excellent idea imo
