### ISSUE TITLE
TR1X bug: Divergence in camera behaviour when sliding down slope - Tomb of Tihocan

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1451]
**OG:**

https://github.com/user-attachments/assets/d274d1f9-34b6-45e0-8bfe-dfb4ced58d1c

_____________________

**Regression since:** [4.1](https://github.com/LostArtefacts/TR1X/releases/tag/4.1) The camera doesn't get pulled toward Lara before zooming out.

https://github.com/user-attachments/assets/3bdafc7d-ae76-47b8-9488-259af650963c

___________________

**Regression since:** [4.3](https://github.com/LostArtefacts/TR1X/releases/tag/4.3) The camera sinks down when Lara is approaching.

https://github.com/user-attachments/assets/150d6afe-ba69-4b4b-8e89-70fe35fe8233

**Comment by lahm86** [comment]
The first issue is related to #1317. The fix for the camera being thrown through doors results in this (no LOS check to Lara) so currently there isn't a way to have both. I think we'd have to move camera 12 in Tihocan as a potential solution.
The second issue's cause has been identified, fix coming shortly.
