### ISSUE TITLE
Bacon Lara re-spawns after save/load

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1500]
To reproduce, complete the bacon Lara room as normal in Atlantis. Once she is in the pit, save and load, and she will go back to mirroring behaviour.

**Comment by rr-** [comment]
Can we check which version broke this?

**Comment by aredfan** [comment]
This issue is a regression since [0.7](https://github.com/LostArtefacts/TR1X/releases/tag/0.7). You can try it out with this save: [saveati.zip](https://github.com/user-attachments/files/16975042/saveati.zip)


In [0.6](https://github.com/LostArtefacts/TR1X/releases/tag/0.6), you'll need to complete the puzzle without saving and loading until after bacon Lara had fallen into the pit, otherwise her movements will break.  After bacon Lara is in the pit, save and reload and there's no issue. I've confirmed this to be the case with this save: [saveati (2).zip](https://github.com/user-attachments/files/16975045/saveati.2.zip)
