### ISSUE TITLE
OG bug: Lara can get stuck in her hit animation on the boat and skidoo

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1606]
Apparently this is an OG bug, demonstrated here on TR2R. In short: when Lara is in an animation state of being attacked in the very moment she mounts the skidoo, her model won't update to her sitting on it.
https://youtube.com/shorts/2xxeUq0E0PQ?si=GSJqvffjQoso5H8Z

Would be good to test for the boat too.

**Comment by aredfan** [comment]
I'm able to reproduce this bug in OG (TR2Main).  Lara can also get stuck in a different state if she's attacked from the side instead of behind:

![2](https://github.com/LostArtefacts/TRX/assets/94776985/2fcafb00-128a-4e31-9812-d07d9e1e545f)

If Lara is killed on the skidoo while in this state, she stays suspended in the air like Randy and Rory does in Temple Ruins:

![3](https://github.com/LostArtefacts/TRX/assets/94776985/f4c6a109-6937-4301-8734-448d54a243ee)

**Comment by walkawayy** [comment]
This also affects the boat

![image](https://github.com/user-attachments/assets/5c5faf7f-da4d-4f1f-8a0a-90e3e6198d35)
