### ISSUE TITLE
Add Bartoli sunset dome (PS1)

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1618]
This would need some more details on how it behaves, but on the PS1, the sky texture changes over time to simulate a sunset.

At the end of the level:
![SLUS-00437_2023-11-07_23-55-52](https://github.com/LostArtefacts/TRX/assets/4934209/6101ccc3-0933-414a-94bd-ae8fca07421a)

It makes sense since the following Opera House is set at night.

**Comment by aredfan** [comment]
The skybox looks the same on PC, from the same spot.

![1](https://github.com/LostArtefacts/TRX/assets/94776985/f8b7fd82-1b77-4fd2-bd60-034b3e2cc54f)

**Comment by Richard-L** [comment]
Ah interesting. Somehow people seemed adamant it was a PS1 only thing, but looks like that's not true.

**Comment by aredfan** [comment]
@Richard-L is it okay to close this issue since we've established the skybox is the same on PS1 and PC?

**Comment by Richard-L** [comment]
@aredfan I think you are right and we can likely close this, since the skybox seems to exist (unfortunate your image link above broke but I remember it).

Just one question for me remains, in light of the darkening of the level https://github.com/LostArtefacts/TRX/issues/1617: From what moment on will the skybox be swapped?

Is this after a certain time elapsed in the level?

Is it due to a trigger in a room somewhere?

Just keen to make sure it's working as on PS1.

**Comment by aredfan** [comment]
> Just one question for me remains, in light of the darkening of the level #1617: From what moment on will the skybox be swapped?

There is just one skybox in this level.  It can be quite misleading at the beginning because Lara is surrounded by tall buildings and can only see the top of the skybox which is all blue.

![1](https://github.com/user-attachments/assets/5a076131-58a7-4b9e-b56d-44e2f62edfdc)

When Lara gets to higher ground, that's when she can see the sunset clouds which are closer to the horizon than the top.

![2](https://github.com/user-attachments/assets/a86a68e4-d812-412b-bfce-6287b71cf812)

**Comment by Richard-L** [comment]
Thanks a lot for clarifying!
