### ISSUE TITLE
TR2X bug: visible overlap of rooms in The Deck

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#1853]
**Regression since:** [0.6](https://github.com/LostArtefacts/TRX/releases/tag/tr2-0.6)
_______________

**Steps to reproduce:**

1. `/play 10`
2. `/tp 51 4 48`
3. move the camera until you can see the rooms overlapping

![20241108_195122_The_Deck](https://github.com/user-attachments/assets/061ce90b-d913-40b7-92b1-023201158d03)

**Comment by lahm86** [comment]
This is a strange one. It seems like a data issue - room 17 has a visibility portal into room 104 (which is clearly wrong, must have been a level editing bug), and in turn because that is linked to room 80, room 80 is drawn. The portal is marked by the waypoints here, just imagine it pointing downwards to room 104.

![image](https://github.com/user-attachments/assets/dc70c3b5-b1b8-47ae-bca6-a00870b2be11)

I'm not sure where the regression is if this doesn't happen in OG. Ideally we would fix the data and the regression itself.

**Comment by aredfan** [comment]
Thanks for providing a detailed breakdown there Lahm.

Btw this issue also manifests in the upper end of the level where Lara picks up the last key.

![20241109_072217_The_Deck](https://github.com/user-attachments/assets/7cfe39e8-6a92-44bc-861e-9806c88121c5)

**Comment by lahm86** [comment]
This seems to have been caused by https://github.com/LostArtefacts/TRX/commit/6c365499e529de0c0f0cf2ab152515a82f91881b. Restoring the various `g_FltWinLeft = g_PhdWinMinX; //...etc` calls in `output.c` that were removed in that commit fixes it, but there are side effects:

- Restoring in `Output_InsertRoom` fixes the main problem, but 3D pickups aren't shown in-game, and the inventory is empty.
- Restoring in `Output_InsertRoom` and `Output_InsertPolygons` fixes the problem and pickup/inventory display, but the 3D pickups appear centre-screen.

![image](https://github.com/user-attachments/assets/f47c7000-0a67-4db8-b52e-a8fffe5eac36)
