### ISSUE TITLE
Improve translation support for text under passport

### ISSUE THREAD

**Issue by antonio3687** [LostArtefacts/TRX#1971]
![20241128_220922_El_coliseo](https://github.com/user-attachments/assets/d4a44125-9e54-45b2-936a-e93dbb744786)
![20241128_220937_El_coliseo](https://github.com/user-attachments/assets/f8049693-87a8-464d-8adc-632fe3e943a1)
![20241128_221138_El_coliseo](https://github.com/user-attachments/assets/de1fd629-3433-4995-8ffc-f9ed685ffd78)
Good evening, did you fix the textures in the coliseum level or am I confused? The texts are joined with the arrows as seen in the attached images, the texts of the main menu also happens the same. Greetings and thank you very much.

**Comment by aredfan** [comment]
Hi @antonio3687, you're correct that the Colosseum roof textures have been changed. The new roof texture is taken from a beta version of Tomb Raider 1, and is added to TR1X when using the `Fix texture issues` option in the config.

The grey arrows issue is probably because it has a fixed position and doesn't shift dynamically if the text string gets longer.
