### ISSUE TITLE
Feature request: Prevent Lara from automatically throwing away a flare while in the air

### ISSUE THREAD

**Issue by rondeeno** [LostArtefacts/TRX#1989]
[FLEP](https://github.com/FlexiblePatcher/FlexiblePatcher) has a "safe flare throw" patch for custom TRNG levels that prevents Lara from automatically throwing away a used flare while jumping or falling, which would be a nice feature to have in TR2 since it helps prevent deaths where Lara prioritizes throwing away a flare over grabbing a ledge/ladder.

**Comment by Richard-L** [comment]
Had a look at Flep but there's virtually nil info about the patches or who's making them?

Fwiw the infamous issue that Lara doesn't grab because she's distracted disposing a flare also happens in TR3. There are also a few variants of it with climbable walls, etc.

Perhaps a grab could just always cancel the "dispose flare" animation?

And what if a user wants to throw a still burning flare? Would that count as their mistake to have mistimed the throw in a moment they needed to grab?

**Comment by rondeeno** [comment]
> Had a look at Flep but there's virtually nil info about the patches or who's making them?

The repository I linked seems to just be for releases. Here's the [forum thread](https://www.tombraiderforums.com/showthread.php?t=229610) with more information and the commit that added the safe flare throw patch: asasas9500/flep@9a70d7e
> Perhaps a grab could just always cancel the "dispose flare" animation?

That would actually probably be ideal. The only thing is I don't know how that would look since there aren't any transition animations made for it.
> And what if a user wants to throw a still burning flare? Would that count as their mistake to have mistimed the throw in a moment they needed to grab?

Players should still be able to manually throw flares while jumping/falling imo, since Lara's guns can be drawn in the same circumstances (which also leads to her failing to grab a ledge/ladder).
