### ISSUE TITLE
Texture mapping changes when toggling bilinear filtering

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#2013]
The size of the textures seems to grow by 1-2% when bilinear filtering is on and some image data is lost. Perhaps would this be a placeholder for later edge blending?

https://github.com/user-attachments/assets/24a7cbe4-1bb0-415b-96f7-bc474488fee2

**Comment by rr-** [comment]
Actually that's intended, and it can be disabled by setting the `texel_adjust_mode` option to `never`. (If you use `/set`, remember to reload the level to see the effect.) But doing this will result in ugly visuals.
![20241212_225038_Laras_Home](https://github.com/user-attachments/assets/4ad3467e-c320-4131-b6f7-ca422d78397d)

**Comment by Richard-L** [comment]
Ah that's unfortunate. I guess the lines can't be fixed straightforwardly.

**Comment by rr-** [comment]
Yeah – a texture atlas (called a "page" in the TR lingo) combines multiple smaller textures into one large image. When using corner coordinates for texture mapping, the bilinear sampler may blend pixels from nearby textures, leading to visual artifacts. This happens because the sampler pulls pixel values from areas around the coordinates, which includes parts of adjacent textures. Offseting the corners by half a pixel prevents this from happening and is how it's done in TR1/TombATI.
