### ISSUE TITLE
Incorrect UI scaling

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#559]
With higher UI scaling, the text box borders do not increase in size. They remain a constant two pixel size at all scaling levels. Should they increase to possibly 4 pixels at 1.5+scaling and 6 pixels at 2 scaling? There may also need to be a change in the spacing so the borders do not overlap. This is also possibly related to #466.

Here's the highest UI scaling option of 2 and there's still a 2 pixel border size.
![20220514_112454_Title](https://user-images.githubusercontent.com/81546780/168436635-ae73953b-e2b4-47f1-896d-09465da1081b.jpg)

At low resolutions, the UI lines are also wrongly drawn.

**Comment by rr-** [comment]
I'd scale everything proportionally, yes, but also have some minimum weights imposed so that scaling the UI by 0.5 doesn't cause 1px line for the left border and no line for the right border (due to mismatching rounding – this is a popular issue in web browsers), for example, or 0 px for both borders (so that the border is gone altogether due to 0.5 getting rounded down to 0).
