### ISSUE TITLE
Feature request: installer

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#584]
The installer should support the following use cases:

- install from scratch from the Steam
- install from scratch from the GOG version
- install from scratch from a CD drive (CD drive autodetection can be delivered post 2.10)
- install from scratch from the specific directory
- update existing t1m installation

Additionally the user should be able to override the source directory and specify the target directory.

I already have a wizard GUI for this in mind.

**Comment by Richard-L** [comment]
I could have sworn we had an issue for it from a couple of months ago but I can't find it.

You beat me to it. Just sadly didn't have enough free time to make some UI designs suggestions for this like I'd been meaning to.

I would make the update check automatically upon launcher start, prompt available updates with changelog, and allow to install or skip. A more advanced feature could be something almost like a version browser, allowing the user to choose up or down between any versions. Essentially a convenient downgrader should something break. Can always be done manually of course by downloading older builds from Github, and thus isn't too important. Just a thought.

What I'd love to see of course was something like an asset configurator. So for example if I provide both an original PC CD and a PS1 CD, it would list it has detected both FMV sets for example, and let me choose between them. The same would theoretically go for level files, to give people access to Japanese levels and their small obscurities, or the different versions circulating for TRUB (with or without music triggers, etc). It would also be terrific if something like SFX could be parsed from a PS1 CD, so people who wish to use things like the PAL Uzi sound could do that instead of the PC version's sound. Whatever assets are chosen could then be saved as "configurations", which could then be chosen based on what the user wants to play on that day. Pretty crazy of course, and thus probably something for maybe later, if at all :pray: 

Speaking about these configurations: it would be terrific if all of TR1M's features were at some point part of the launcher. To avoid having people fiddle with JSONs, and to establish speedrunner community approved configuration settings, that can be loaded and assure a speedrunner the resulting rendition of TR1 is safe to use. Would allow a good starting point for dialogue with the speedrunning community.

The other immediate community to potentially "endorse" would be TRLE. The launcher would suit itself as a browser for TRLE.net's database, and allow people to pick levels and then automatically fetch and save data in the required folders, making any level immediately available with no added config work for the end user. Would be a chance to suggest a collaboration with TRLE.net, also in light of TR2 and 3 later perhaps.

**Comment by rr-** [comment]
I think we have some confusion here; an installer is not a launcher. Its only task is to extract files from a Steam / GOG / CD / existing T1M installation to a target directory and install T1M over it. Things such as changelogs, automatic updates and a trle browser are not a part of its scope. That's not to say they can't be implemented some other day.

>Asset configurator

Too much for me, maybe someone else can provide this in the future.

>Simpler config and a GUI config tool

2.11 (hopefully)

>TRLE.net

Check out https://trcustoms.org ;) I'd keep it as a link in the launcher. But again that's out of scope for this ticket.

**Comment by Richard-L** [comment]
I know most of that is out of scope/too much but I thought it's worth sharing ideas anyway. Launcher/installer, to the end user won't make much of a difference what you call it. Essentially we need an assistant application that enables QoL, as that's the only way to win people beyond who are already here. And even just installing things the right way will be a good step in that direction.

And I forget what the right TRLE urls are :p
