### ISSUE TITLE
Game stutters for a few seconds when new music loads

### ISSUE THREAD

**Issue by ghost** [LostArtefacts/TRX#589]
Hello.
I installed TR1 GOG version and then installed this:
https://github.com/Carlmundo/TombRaider-AutomatedFix
With improved FMVs before installing Tomb1Main.
When new music loads the game seems to stutter for a few seconds and then the game is fine.
This happens every time new music loads in.
Not sure if its a bug or something wrong that I did.
I hope there is a solution for this.
BTW I am using the latest stable release as well.
My OS is Windows 11 and it's a laptop with a dual GPU setup of AMD/Intel.

**Comment by walkawayy** [comment]
This issue reporter deleted their account but this might be related to #686 where the game is using the integrated instead of the dedicated GPU.

Also maybe the automated fix messed with things?

**Comment by Richard-L** [comment]
I also have a laptop with dual GPU of Intel/Nvidia, and if the Intel chip is used the game tends to stutter a lot in general. So my hunch is it's that.
Would be good however to see again what the automated fix does exactly to the assets. But since the user heard music _at all_, it seems the format is fine.

**Comment by walkawayy** [comment]
I think the goal is to address performance in the future if we can. But this user deleted their Github account, so I closed this issue. We can address it if someone new reports it.
