### ISSUE TITLE
Some saves can no longer be loaded

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#620]
With enhanced saves on, the following issue was found if you save/load at various points through Atlantis. The last save will no longer load. When enhanced saves are off, this issue does not appear.

https://streamable.com/zmlmkb (issue occurs from 02:40)

The following is in Tomb1Main.log

```
../src/game/savegame/savegame_bson.c 562 SaveGame_BSON_LoadFx Malformed save: expected a max of 99 fx, got 99
../src/game/game/game.c 141 Game_Start Failed to load save file!
```

Save files:
[Saves.zip](https://github.com/rr-/Tomb1Main/files/9538607/Saves.zip)

Found by NaBu1908 during rando testing - above is original level file data.

**Comment by walkawayy** [comment]
So the error happened because I had a `>=` instead of a `>` during the loading process. But looking at what FX were being restored was interesting. Since lava emitters remain active, 98/99 loaded FX were `O_LAVA` which are the little lava particles the lava emitters shoot out. Atlantis has 7 lava emitters and near the end of the level all are active. And they shoot out a good number of particles so the 99 limit is reached. I played a little further in the save and it seems like gunshot sprites, mutant explosions, etc all still were drawn correctly even though the FX array was full. I might debug a little further.
