### ISSUE TITLE
Sounds are stopped completely in inventory/pause under certain conditions

### ISSUE THREAD

**Issue by Rapora9** [LostArtefacts/TRX#717]
Conditions: `Enable game sounds in inventory` is DISABLED and `Do not stop music on secrets pick-ups` is ENABLED.

If you go to inventory/pause when the secret sound is playing, the sound is killed completely and won't resume when you continue the game. The sound continues normally if _Do not stop music on secrets pick-ups_ is DISABLED.

**Comment by walkawayy** [comment]
The secret track is very short, and you opted to disable sounds in inventory, so I don't think this is a bug. But I'll tag @rr- to confirm. 

Basically the `Do not stop music on secrets pick-ups` fix works by playing the sound effect version of the secret sound instead of the music version. That's done so the game doesn't stop the currently played music by playing the secret "music". As a result, the secret sound effect can't be paused and resumed like a music track.

**Comment by Rapora9** [comment]
I do think it's a clear bug, but seeing how the "do not stop music" solution is done, I understand why it doesn't allow this to be fixed.

Can be closed after rr has taken a look.

**Comment by rr-** [comment]
I would say this is a bug and is worth fixing.
I'd also make another feature which would be to pause and unpause sound effects when in the pause/inventory screen. But that's a separate thing.

**Comment by Rapora9** [comment]
Wonderful! I was actually hoping for sounds to be paused and resumed too, but didn't dare to ask for it 😅
