### ISSUE TITLE
Make menu keybinds independent of in-game controls

### ISSUE THREAD

**Issue by OpenRift412** [LostArtefacts/TRX#804]
One oversight I've noticed with Tomb1Main is that the controls for navigating the menu are tied to the keybinds you have set for controlling Lara in-game. From what I can tell, this isn't something that's present in the original DOS version, either.

**Comment by Richard-L** [comment]
I think this is what walkaway intended when he redid the control mappings a few months ago. It takes some getting used to at first, but after makes a lot of sense.

**Comment by OpenRift412** [comment]
> I think this is what walkaway intended when he redid the control mappings a few months ago. It takes some getting used to at first, but after makes a lot of sense.

That's kind of silly. At that point, just make a separate binds list for menu navigation. It's really unintuitive and no other game of the era that I know of, source ports or original, does that.

**Comment by walkawayy** [comment]
Gonna defer to @rr- for a decision on this. I suggested this in the past, but I think we were afraid of angering classic TR fans. The old games did not have separate menu keybinds, and used Lara's controls in the menu. But the classics did have some hard coded buttons for menu navigation and two active control schemes that covered up some issues.

**Comment by rr-** [comment]
Let's wait and see what people think. If there's enough pressure to tackle this, we can separate these buttons.

**Comment by Richard-L** [comment]
Maybe would it be enough to leave the default mapping intact for as long as you haven't completed/exited the mapping dialogue?

I love the way we can do mappings now ever since walkaway's improvements, especially the unbinding of buttons. But whenever there's a new TR1M release and I remap everything, I can understand that it's strange how the down arrow key you use to step through the mappins suddenly stops responding the moment you remap "down", and you immediately have to use your new key for it.

**Comment by rr-** [comment]
That makes perfect sense and I endorse this behavior. I think it should act this way regardless of whether we split the menu navigation from Lara's navigation keys or not.

**Comment by walkawayy** [comment]
Closing this as duplicate since menu keybinds will come back as a result of #814.
