### ISSUE TITLE
Lara can't flip off crumbling floors with fix_descending_glitch enabled

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TRX#830]
3 reports that there is input lag. This is most noticeable in Atlantis's throne room where you can't backflip off the trap doors after pulling the switches. I would guess this is an OG bug but idk.

https://www.tombraiderforums.com/showpost.php?p=8398576&postcount=426

**Comment by walkawayy** [comment]
Seems like this might be the result of the `fix_descent_glitch` option. In which case I don't think this is a bug.

https://www.tombraiderforums.com/showpost.php?p=8399008&postcount=429

**Comment by rr-** [comment]
After quick conversation on Discord – the option that changes this behavior is about fixing Lara teleporting down when she sidesteps on breakable tiles. The reports are about broken jump off trapdoors after pulling a switch, which should be irrelevant to that option, and the problem is that it is somehow related. The fix for the first bug shouldn't affect the latter, which is pretty canon IMO and should stay regardless of this setting.
