### ISSUE TITLE
Overzealous walk to pickup

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TRX#834]
Lara shuffles her feet even when she's standing literally on the item she's about to pick up. Let's check if we broke something recently related to this. If not, let's expand the walk activation radius to something more sensible, and check the radii for this feature to work in general.

**Comment by walkawayy** [comment]
Possible differences I'm gonna post to more easily reference...

TR1 `Item_Move3DPosTo3DPos`:
```
        src_pos->x += (x * velocity) / dist;
        src_pos->y += (y * velocity) / dist;
        src_pos->z += (z * velocity) / dist;
```

TR5 `Move3DPosTo3DPos`:
```
		shift = 65536 * speed / distance;
		pos->x_pos += shift * dx >> 16;
		pos->y_pos += shift * dy >> 16;
		pos->z_pos += shift * dz >> 16;
```

EDIT: Not this. Using both formulas yields the same xyz pos.

---------

TR1 `Lara_MovePosition` (also, `ITEM_ADJUST_ROT` called before this in `Item_Move3DPosTo3DPos`):
```
        int32_t angle = (PHD_ONE
                         - Math_Atan(
                             g_LaraItem->pos.x - item->pos.x,
                             g_LaraItem->pos.z - item->pos.z))
            % PHD_ONE;
        uint32_t quadrant =
            ((((uint32_t)(angle + PHD_45) >> W2V_SHIFT)
              - ((uint16_t)(item->pos.y_rot + PHD_45) >> W2V_SHIFT))
             & 0x3);
```

TR5 `Move3DPosTo3DPos` (rots are adjusted after this determines Lara's WASD direction):
```
			ang = ulong(mGetAngle(dest->x_pos, dest->z_pos, pos->x_pos, pos->z_pos) + 0x2000) / 0x4000;
			quad = ushort(dest->y_rot + 0x2000) / 0x4000;
			ang -= quad;
			ang &= 3;
```

EDIT: Both formulas yield the same quadrant.

**Comment by walkawayy** [comment]
This broke in this commit: https://github.com/LostArtefacts/Tomb1Main/commit/6f7fe4c2a1b24888ddd950a6ec0c058d37c74402

`angle` and `quadrant ` are now using `item` values. They need to use `dst_pos` which is different. Since you did the refactor, I didn't make any fix. Idk how you want the code to look, so I'll leave it up to you?

This will also fix issues with pulling switches. I remember it causing issues in Sabatu's TR1 because Lara would take a long step back before pulling a switch every time and it ruined a timed section. This option had to be disabled because of it. I thought it might have been a TR1 asset issue and forgot to look into it.

**Comment by rr-** [comment]
From code inspection alone, I don't see it - pointers seem to be all the same (`srcpos = g_LaraItem->pos`), and the order of the operations didn't change?

Never mind, I see a difference - the walk to items shenanigans used to happen before `ADJUST_ROT` but now are executed as an afterthought in case the item is Lara. Is this the reason?

I prefer the design where we specialize moving item positions for Lara inside Lara routines. If it's not feasible to keep it this way, we can go back to the previous order and do `if (item == g_LaraItem)`.

**Comment by walkawayy** [comment]
It took me way too long to realize too.

In `Item_MovePosition`, the variable `PHD_3DPOS dst_pos;`is created and its `rot`s and `xyz` values get set. `dst_pos` then gets passed to `Item_Move3DPosTo3DPos`. In that function, it moves Lara closer to the pickup, but when she is close enough, Lara's `xyz` get set to `dst_pos`'s `xyz`. In your refactor, that function then returns by properly checking if Lara's `rot`s and `xyz`s are equal to `dst_pos`'s `rot`s. The problem occurs when it returns to `Lara_MovePosition` where the `angle` and `quadrant` calcs then use `item`'s `rot`s and `xyz` values instead of `dst_pos`'s. The `angle` and `quadrant` calcs previously occurred in `Item_Move3DPosTo3DPos` when it was working properly.

LMK if that makes sense.

Also side note, `step_to_anim_num` and `step_to_anim_state` can probably get changed to statics?

**Comment by rr-** [comment]
Let's restore the previous order of calls and move the Lara check back to where it was, but let's also add the check `if (item == g_LaraItem)`.

>Also side note, step_to_anim_num and step_to_anim_state can probably get changed to statics?

They can but polluting the global state inside this module isn't worth it IMO.

**Comment by walkawayy** [comment]
1. My wild thought is what if we just modified `Item_MovePosition` to actually move the item and get rid of `dst_pos` altogether? The current function names already suggest that's what should be happening, but in the current form the item isn't actually moving. And, at the end of `Pickup_CollisionControlled`, we are already restoring the item `rot`s:
```
    item->pos.x_rot = rotx;
    item->pos.y_rot = roty;
    item->pos.z_rot = rotz;
```
Could we just save off the `xyz` positions too at the beginning of the pickup function and restore it?

2. Another option could be to create `dst_pos` much earlier in `Pickup_CollisionControlled` and send that through the entire chain of functions instead of `item`. The function names would need to change since it's no longer an `item`, but like I said earlier, idk if the current names fit anyway. `Item_MovePosition` and `Item_Move3DPosTo3DPos` are only used for pickups, so we could change some things without breaking anything else. It's only other use is underwater pickups.


And my thought for the quadrant arrays would be something like:
```
const int16_t m_StepToAnimNum[4] = {
            LA_SIDE_STEP_LEFT,
            LA_WALK_FORWARD,
            LA_SIDE_STEP_RIGHT,
            LA_WALK_BACK,
};
```
so they wouldn't be global. Unless you mean global within `lara.c`? In which case that makes sense I guess.

**Comment by rr-** [comment]
@walkawayy it's difficult for me to visualize this change, could I see a diff or a pseudodiff that shows the changes you have on your mind?

**Comment by walkawayy** [comment]
For example, here's a patch for option 1 above as a proof of concept (works in all cases expect with walk to items OFF underwater, so some changes would need made in that function). Notice `dst_pos` which is the tricky part of all this.

```diff
diff --git a/src/game/items.c b/src/game/items.c
index f73d28bb..cb7138c9 100644
--- a/src/game/items.c
+++ b/src/game/items.c
@@ -418,26 +420,23 @@
 bool Item_MovePosition(
     ITEM_INFO *src_item, ITEM_INFO *dst_item, PHD_VECTOR *vec, int32_t velocity)
 {
-    PHD_3DPOS dst_pos;
-    dst_pos.x_rot = dst_item->pos.x_rot;
-    dst_pos.y_rot = dst_item->pos.y_rot;
-    dst_pos.z_rot = dst_item->pos.z_rot;
     Matrix_PushUnit();
     Matrix_RotYXZ(
         dst_item->pos.y_rot, dst_item->pos.x_rot, dst_item->pos.z_rot);
     MATRIX *mptr = g_MatrixPtr;
-    dst_pos.x = dst_item->pos.x
-        + ((mptr->_00 * vec->x + mptr->_01 * vec->y + mptr->_02 * vec->z)
-           >> W2V_SHIFT);
-    dst_pos.y = dst_item->pos.y
-        + ((mptr->_10 * vec->x + mptr->_11 * vec->y + mptr->_12 * vec->z)
-           >> W2V_SHIFT);
-    dst_pos.z = dst_item->pos.z
-        + ((mptr->_20 * vec->x + mptr->_21 * vec->y + mptr->_22 * vec->z)
-           >> W2V_SHIFT);
+    dst_item->pos.x +=
+        ((mptr->_00 * vec->x + mptr->_01 * vec->y + mptr->_02 * vec->z)
+         >> W2V_SHIFT);
+    dst_item->pos.y +=
+        ((mptr->_10 * vec->x + mptr->_11 * vec->y + mptr->_12 * vec->z)
+         >> W2V_SHIFT);
+    dst_item->pos.z +=
+        ((mptr->_20 * vec->x + mptr->_21 * vec->y + mptr->_22 * vec->z)
+         >> W2V_SHIFT);
     Matrix_Pop();
 
-    return Item_Move3DPosTo3DPos(&src_item->pos, &dst_pos, velocity, MOVE_ANG);
+    return Item_Move3DPosTo3DPos(
+        &src_item->pos, &dst_item->pos, velocity, MOVE_ANG);
 }
 
diff --git a/src/game/objects/general/pickup.c b/src/game/objects/general/pickup.c
index 96af7e0a..ca7dc9e9 100644
--- a/src/game/objects/general/pickup.c
+++ b/src/game/objects/general/pickup.c
@@ -146,13 +146,19 @@ void Pickup_CollisionControlled(
     }
 
     bool have_item = false;
-    int16_t rotx = item->pos.x_rot;
-    int16_t roty = item->pos.y_rot;
-    int16_t rotz = item->pos.z_rot;
+    int32_t orig_x = item->pos.x;
+    int32_t orig_y = item->pos.y;
+    int32_t orig_z = item->pos.z;
+    int16_t orig_rotx = item->pos.x_rot;
+    int16_t orig_roty = item->pos.y_rot;
+    int16_t orig_rotz = item->pos.z_rot;
+
     item->pos.y_rot = lara_item->pos.y_rot;
     item->pos.z_rot = 0;
 
     if (g_Lara.water_status == LWS_ABOVE_WATER) {
+        item->pos.x_rot = 0;
+
         if ((g_Input.action && g_Lara.gun_status == LGS_ARMLESS
              && !lara_item->gravity_status
              && lara_item->current_anim_state == LS_STOP
@@ -161,7 +167,6 @@ void Pickup_CollisionControlled(
                 && g_Lara.interact_target.item_num == item_num)) {
 
             have_item = false;
-            item->pos.x_rot = 0;
 
             if (Lara_TestPosition(item, m_PickUpBoundsControlled)) {
                 m_PickUpPosition.y = lara_item->pos.y - item->pos.y;
@@ -225,9 +230,12 @@ void Pickup_CollisionControlled(
             g_Lara.gun_status = LGS_ARMLESS;
         }
     }
-    item->pos.x_rot = rotx;
-    item->pos.y_rot = roty;
-    item->pos.z_rot = rotz;
+    item->pos.x = orig_x;
+    item->pos.y = orig_y;
+    item->pos.z = orig_z;
+    item->pos.x_rot = orig_rotx;
+    item->pos.y_rot = orig_roty;
+    item->pos.z_rot = orig_rotz;
 }
 
 bool Pickup_Trigger(int16_t item_num)
diff --git a/src/game/objects/general/switch.c b/src/game/objects/general/switch.c
index 190ea834..21c2564f 100644
--- a/src/game/objects/general/switch.c
+++ b/src/game/objects/general/switch.c
@@ -118,6 +118,13 @@ void Switch_CollisionControlled(
 {
     ITEM_INFO *item = &g_Items[item_num];
 
+    int32_t orig_x = item->pos.x;
+    int32_t orig_y = item->pos.y;
+    int32_t orig_z = item->pos.z;
+    int16_t orig_rotx = item->pos.x_rot;
+    int16_t orig_roty = item->pos.y_rot;
+    int16_t orig_rotz = item->pos.z_rot;
+
     if ((g_Input.action && g_Lara.gun_status == LGS_ARMLESS
          && !lara_item->gravity_status
          && lara_item->current_anim_state == LS_STOP
@@ -167,6 +174,12 @@ void Switch_CollisionControlled(
         && lara_item->current_anim_state != LS_SWITCH_OFF) {
         Object_Collision(item_num, lara_item, coll);
     }
+    item->pos.x = orig_x;
+    item->pos.y = orig_y;
+    item->pos.z = orig_z;
+    item->pos.x_rot = orig_rotx;
+    item->pos.y_rot = orig_roty;
+    item->pos.z_rot = orig_rotz;
 }
 
 void Switch_CollisionUW(int16_t item_num, ITEM_INFO *lara_item, COLL_INFO *coll)
```

**Comment by rr-** [comment]
Looks good to me; but I'd simplify the `pos` restoration to use the underlying struct type and assign directly to `pos`. https://stackoverflow.com/questions/2302351/assign-one-struct-to-another-in-c#:~:text=Yes%2C%20you%20can%20assign%20one,address%20of%20the%20other%20pointer.

**Comment by walkawayy** [comment]
Ok. I'll do a little more thinking on it too, since this also affects switches, special cases like the Scion and Midas lead, and underwater pickups even with walk to pickups off.
