### ISSUE TITLE
OG bug: Natla's right arm still target Lara after first death

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#878]
Mentioned before in #875 but I thought it'll be a good idea to create an issue for it.

https://github.com/LostArtefacts/Tomb1Main/assets/94776985/e968e162-faf3-4aec-a66e-9aca3f9648f0

**Comment by Richard-L** [comment]
It's confronting (in a good way) to think that these small bugs are found so many years later.

**Comment by lahm86** [comment]
I've also seen her spin on the floor occasionally, but I can't reproduce it easily. Could be worth investigating properly as part of this. 

Apologies too @aredfan - I meant to comment in #875 that you were right, it wasn't related to bacon Lara's movement as that was because her draw routine is shared with Lara's, but it didn't account for her current state. Good to get it raised as its own issue.

**Comment by walkawayy** [comment]
Natla doesn't seem to target me @aredfan ? Are there certain conditions for it to happen?

![image](https://github.com/LostArtefacts/Tomb1Main/assets/81546780/bd9a2065-3f92-423d-9cb4-ae970d355a94)

**Comment by aredfan** [comment]
That's weird.  I'm unsure whether there's a condition that causes Natla's arm to continue targeting Lara.  You might have to walk around her body to trigger a response.

Load this save file and run forward: https://drive.google.com/drive/folders/1lmEvviNjH73aj4Y9nRzeg8pPNoq0U1vA?usp=sharing
