### ISSUE TITLE
More streamlining for custom levels

### ISSUE THREAD

**Issue by mizunosuisei** [LostArtefacts/TRX#882]
After noticing that tomb1main updates don't work unless you also replace the gameflow file, this leaves custom levels slightly in the lurch. Ofcourse it's easy enough to copy and paste their custom gameflow text into the updated gameflow, many wouldn't know how/bother to do this.

The only (far off) suggestion I can think of is to have all the injection data in a different cfg file that doesn't relate to per level entries, yet that feels against the purpose ofcourse - or allow the game to run regardless if injection data is/isn't there.

**Comment by lahm86** [comment]
An update will he coming soon to enforce the gameflow to be updated when using the installer. Custom level builders have the tools available to them to update the script for their games, Tomb1Main cannot be responsible for that. Indeed, it is prudent for builders to check what is and what is not relevant to inject into their games. For example, `caves_textures.bin` contains spexif

Other gameflow changes such as recent remove or add new sequence types. These are again essential to how the game works, the latest being that bacon Lara's position is now customizable. This level of customization comes at the cost of

**Comment by lahm86** [comment]
_Apologies for closing this before replying initially, I hit the wrong button._ 

We are looking at a change to how the gameflow is updated via the installer such that it will always be updated on new release. 

I think for level builders, careful checks should be done to see what is and what is not relevant to inject into their games as Tomb1Main cannot be responsible for that. For example, texture fix files for OG levels will not be required in custom levels, so builders should remove those entries.

Other recent changes involve gameflow sequence updates, and these are essential to how the game plays out, so it's normal imo that the game should not load when something is missing or incorrect.

**Comment by mizunosuisei** [comment]
Thankyou for your response :) I'm really not knowledgeable with the indepths of it all.

Just throwing this one - it could be laughable- but wouldn't it possibly be a more novel idea to force tomb1main to load regardless if the data folder contains bin injections, and the script does not? I'm mostly thinking around this for older customs too.

**Comment by rr-** [comment]
>Change the installer to have gameflow always updated

Do we have an issue for this?

>Gameflow woes

Level authors should make updates to the gameflow in a conscious and controlled manner; I don't think it needs to be said but expecting a drag-n-drop of the gameflow file to work is misplaced.  Now, I don't think our updates to the bundled gameflow are revolutionary either – drag-n-drop of a new Tomb1Main.exe to an old level should work fine. (Correct me if I'm wrong. If that's not the case, I think we should provide some reasonable amount of backwards compatibility around this.)

>Different file for injections, custom levels using injections

Injections were made solely because we don't have the means nor want to change OG levels. Custom levels have complete freedom over what they include, whether it's the braid, or something else. As such, like Lahm said, including injection files for custom levels makes little sense.

That said, I'm fine to defaulting to a warning instead of erroring out, if a .bin level file with an injection is missing while the gameflow requests it to load. Is this what you had in mind?

**Comment by mizunosuisei** [comment]
I think that sounds like a marvelous idea! Honestly my whole train of thought surrounds older customs where authors may not even be around anymore to create their own customized gameflow. Many many players also wouldn't even know where to begin to make them compatible. I'm part of a large community with many players are not in the generations you'd expect- so I keep these players in mind


Thankyou for your input :)
