### ISSUE TITLE
Feature: Add 35fps mode from the 320x200 DOS version? EDIT: non-issue, game logic is 30fps

### ISSUE THREAD

**Issue by VirtuaVespa** [LostArtefacts/TRX#895]
Hello, so from my understanding 320x200 DOS resolution games ran at line doubled 70hz/35fps (like Doom) on VGA monitors and I was wondering if 35fps is somewhere in the code and would be easy to add as an option for people playing on a PC CRT? I read DOS Tomb Raider has two resolutions, 640x480@60hz (which I assume is 30fps?) and 320x200 which I think ran line doubled (640x400) @70hz/35fps?

I might be wrong about this so any explanation as to why it's not a thing is also welcome. Thank you

**Comment by oziphantom** [comment]
The game only runs logically at 30fps. However its is highly probably that the DOS 320x200 version runs 30fps logic at 35fps due to the sync rate of the monitor. This means that playing the game on PC would be 14% faster vs the PS1 version assuming your PC was fast enough to handle it. If it didn't you would see screen tearing which should be easy enough to notice in a video recording of it. Although sadly I don't know of any, the Digital Foundry video doesn't even cover it.

**Comment by VirtuaVespa** [comment]
Super interesting, oziphantom! the 320x200 version is 14% faster?! I've seen nobody talk about this, amazing!

**Comment by oziphantom** [comment]
I guess its one of those things that has been lost to time. I.e anybody these days would take the 640x480 option, This version even just outright removes support for 320x200 as it was to much pain to make the new GUI work. But maybe the DOS box version can shed some light on it. Not sure if it lets you drop to 320x200 or if it forces you to the 3dfx version.

**Comment by VirtuaVespa** [comment]
Very good info, maybe some others will find this thread who also wonder about 70hz/35fps.

**Comment by Richard-L** [comment]
Well if you play with DosBox it runs at plain normal 30fps. Also if you look up old TR1 DOS footage on youtube, it's always 30fps max. I don't think 35fps is a thing.

**Comment by VirtuaVespa** [comment]
I believe oziphantom has cleared this issue up and said TR1's logic runs at 30fps. Do you mean 35fps isn't a thing for DOS games?

**Comment by oziphantom** [comment]
@Richard-L do you have a link to dos footage that uses 320 mode and not 640 mode all the videos I could fine were 640 and high detail. 
But I guess the question is "Does it use mode 13h or ModeX 200 or ModeX 240. 
13h is 70hz and ModeX 320x200 is also 70hz however ModeX 320x240 is 60hz.

**Comment by renansimoes** [comment]
Is it possible to make the game run in 60fps like OpenLara?

**Comment by vvs-** [comment]
60fps is a big pain in OpenLara and OpenTomb as well. You need somehow to keep logic simulation at 30fps and interpolate, but this is extremely hard in practice. That's the source of many serious bugs in these other engines.

**Comment by oziphantom** [comment]
@renansimoes
> Is it possible to make the game run in 60fps like OpenLara?

you need this version https://github.com/oziphantom/Tomb1Main/tree/60fpsredo its old and still needs the Tomb1ATI patch installed so you can then replace the exe and add the DLL and only has Xbox controller support ( might also have PS5 controller support on a code define ) can't remember. It has a couple of "strats" that don't work but the whole game can be completed and has been streamed a few times by people.

**Comment by walkawayy** [comment]
Ya I think the goal would be to get 60 FPS done, not 35.

**Comment by Richard-L** [comment]
This should be original res DOS footage https://youtu.be/BglkoQtFR4U?t=115

Can't remember the story w the 60fps build now. The TLDR was rr wasn't happy because too many artefacts were introduced. Right?

**Comment by oziphantom** [comment]
yeah that is 320x200. It occured to me that TR is not as old as I think it is, its actually 96 so its not VGA is SVGA and I look up the box to confirm. So 320x200@60 is a valid SVGA mode. 

As to why it wasn't merged. There was a couple of minor bugs that I needed to sort out, I was able to fix one pretty easily. Another has popped up. But the main reason given is 
`Things I don't want you to do:
stray from the original game experience. We're not [OpenLara](https://github.com/XProger/OpenLara/). This project aims to be a very faithful rendition of TR1. The users should have the ability to disable any questionable or non-conservative features such as: death counters, compass stats, enemy healthbars, loading screens, savegame crystals, outstanding rendering improvements etc. This is for example why I never merged 60 FPS - even though it offered a 30 FPS mode, it wasn't polished enough to merge.`

**Comment by Richard-L** [comment]
So all this just to say "it wasn't polished enough". A fair concern, and the optionability is obviously the heart and soul of the project.

More importantly though, I wonder why the question _if we can polish it enough_ was never asked.

**Comment by vvs-** [comment]
That's the question. Look at XProger/OpenLara#353 Still not finished after two years.

**Comment by Richard-L** [comment]
Have you played the 60fps build? It's much farther in that respect than OL.

**Comment by vvs-** [comment]
"I don't have time to play ~~with myself~~" or even just build everything :) But after literally spending years of testing OpenTomb and then some testing of OL I know from the first hand experience that TR is a mine field  of hidden surprises which might break original game experience. Speed running is not enough for being sure that it's ok - it's a hard job :(

**Comment by oziphantom** [comment]
It was basically down to 2 issues I think. 
On the St Francis' Folly when you slide down the long slide after fighting Pierre for the first time you can go backwards then drop down on the bottom little slop and then do a backwards vault and you would just land on the secret platform. Which didn't work in 60fps mode. 
And for some reason the bats in level 1 when you killed them stopped just below the floor and not on the floor. 
Walking at very acute angles didn't work either due to compounding error so you ended up going further left or right than you would normally. 
One of the movement directions had a +1 on the grab detection vector to make up for compound error. 

An idea was to run the graphics at 60 and then physics at 30.  
Wall glitching didn't work at 60 but that was an "yeah well" case. 

It had 1000s of hours of testing on it from speed runners, NLNM runs, casual runs, commentary by the original dev runs. You could put it in the hands of casual to experienced players and it would be perfectly completable without any major glitches just that one trick that won't work anymore. Speed-runners won't touch it as it breaks a lot of their glitches and tricks etc.

**Comment by vvs-** [comment]
> On the St Francis' Folly when you slide down the long slide after fighting Pierre for the first time you can go backwards then drop down on the bottom little slop and then do a backwards vault and you would just land on the secret platform. Which didn't work in 60fps mode.

That same bug is present in both OpenTomb and OpenLara as well. And this was a deal breaker for me.

Also, there were jump trajectory changes, collision bugs, slightly different enemy behavior. And there were those occasional animation bugs, like when Lara makes two steps instead of just one _sometimes_ but not always, due to floating point rounding errors. Of course this was amplified thanks to those engines support for TR2-5.

> It had 1000s of hours of testing on it from speed runners, NLNM runs, casual runs, commentary by the original dev runs. You could put it in the hands of casual to experienced players and it would be perfectly completable without any major glitches just that one trick that won't work anymore. Speed-runners won't touch it as it breaks a lot of their glitches and tricks etc.

Did it get the same amount of testing for Unfinished Business? There was that infamous running jump bug at the end of _Atlantean Stronghold_ which made it not completable.

These problems and the fact that it was not solved up to date makes me skeptical about any 60fps mods. But that's just me, of course. And I won't have time to test it myself anyway. But I wish you luck in solving them.

**Comment by naddel91** [comment]
So this is currently the best way to play Tomb Raider 1 on PC?

**Comment by vvs-** [comment]
What are you actually asking about? What in particular should pronoun "this" stand for? Tomb1Main engine? 60fps mod? 30fps frame rate?

**Comment by naddel91** [comment]
So Tomb1Main is currently the best experience for PC?

**Comment by oziphantom** [comment]
Best you can get.

**Comment by naddel91** [comment]
The shaders (water) and lighting effects were cool on OpenLara, but I guess those cannot be implemented into Tomb1Main, right?

**Comment by Richard-L** [comment]
I would recommend you join the Discord for general questions like that. You can find the invite on the landing page of the project. Discussion had ideally been on topic in here. Which I'm not sure is what at this point tbh.
