### ISSUE TITLE
Feature: Jump-twist input handling change to match TR2+

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#931]
Basically do jump + forward, then release both buttons as you immediately press back.  Same in reverse.

Requested by RetroRaider279 on discord

**Comment by Richard-L** [comment]
I never even knew this was a thing in TR2+. It seems hard to have to coordinate whether you're jumping backwards or forwards and then press the respective opposite direction, instead of just roll which is always the same button in both cases. But I presume enough people are used to this old mechanic and will disagree.

For what my opinion is worth, I think it's feature creep. The addition of jump twists to TR1 was already questionable imo, and I know broke a TRLE builder or two's interest in TR1M because it invalidated levels they had spent a long time making.

**Comment by walkawayy** [comment]
> For what my opinion is worth, I think it's feature creep. The addition of jump twists to TR1 was already questionable imo, and I know broke a TRLE builder or two's interest in TR1M because it invalidated levels they had spent a long time making.

The builder can choose to ship a default config or gameflow that removes these features if they'd like. Also, I don't see how this is feature creep when T1M already is a pretty much finished product, so this isn't causing a delay. And, the twist is completely optional. Most people just see it as a QOL move from future TRs. The game already uses tank controls, so most players welcome the improvement. And again, I'm not sure how an optional feature the builder can turn off invalidates a level design.

**Comment by rr-** [comment]
This should be implemented.
