### ISSUE TITLE
Parse floor data into structures

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#941]
Test the feasibility of parsing floor data into structures - for example, a linked list that `FLOOR_INFO` points to - to replace repeated `g_FloorData` looping logic in the codebase. This ticket is mainly for investigation initially and will be padded out as more details are gathered.

- [x] Rename `FLOOR_INFO` to `SECTOR_INFO` and update all relevant variables
- [x] Standardize `x_floor`/`y_floor` variables when used to calculate index into a room's 2D sector array - make `X/Z` the standard
- [x] Introduce struct in `SECTOR_INFO` for `floor` and `ceiling` to store height and tilt values
- [x] Rename `OBJECT_INFO` `floor` and `ceiling` function pointers, and the functions they point to, to be more descriptive of intent
- [x] Make a "master" floor data parser called on level load; for each sector:
  - [x] Set the `tilt` value for floor and ceiling
    - [x] Refactor usage
  - [x] Set the `room_portal` value
    - [x] Refactor usage
  - [x] Set the `is_death_sector` property
    - [x] Refactor usage
  - [x] Set the `trigger`
    - [x] Refactor usage
- [x] Delete relevant globals, such as `g_TriggerIndex`
- [x] Rewrite floor data injection to use the new structured approach (to be investigated)

**Comment by walkawayy** [comment]
I think it might be a good idea to implement some sort of `on_walkable` bool or something similar into the `SECTOR_INFO` struct. That way I think we could basically implement #1429 into the `Room_GetHeight` function instead of having to traverse the sector again later. This was the way we thought originally to do it, but we didn't want to add another global.
