### ISSUE TITLE
Game freezes when jumping into water on Palace Midas level

### ISSUE THREAD

**Issue by wejs123** [LostArtefacts/TRX#968]
The game freezes while only the ambient sound keeps playing. Happens every time when loading [the save](https://github.com/LostArtefacts/Tomb1Main/files/12508154/save_tr1_24.zip) and jumping into the pool below.  

I did a fresh new install (Windows release 2.15.3, GOG version, all default settings), copied the save file and the same issue occurred. 

Nothing changes in the log file before and after the freeze.

![location](https://github.com/LostArtefacts/Tomb1Main/assets/143972242/9ddbfd73-abdb-4f4c-b4bf-c02397bd042d)

**Comment by walkawayy** [comment]
This was fixed in #956 and will be in the next release. Unfortunately your current save is broken for now. 😞 You can replay the level from the beginning (using the select level menu) to restart the level. Or die and use replay level from the passport menu. To avoid this issue, you can turn off this option in the config tool before you replay the level to avoid the bug.

![image](https://github.com/LostArtefacts/Tomb1Main/assets/81546780/1a4bdb2f-41ba-4efb-8076-75d12c4d5682)

**Comment by wejs123** [comment]
Okay, glad to know it's fixed. It wasn't a big problem for me, I had a previous save. Closing the issue.

**Comment by lahm86** [comment]
Reopening this issue as we will add a workaround to allow (what will become) legacy saves to load safely, in addition to the implemented fix in #956.
