### ISSUE TITLE
Release CPU while waiting

### ISSUE THREAD

**Issue by Gerwin2k** [LostArtefacts/TRX#985]
I was trying some profiling to investigate performance on a slower PC. With the new framebuffer rendering that is. But I actually noticed some oddity on my faster PC. CPU usage combined is around 25% all the time. One of 4 real CPU-cores being almost at maximum at all times. With or without vsync. 
GNU Profiler says it spends 70% of the time in this function "S_Clock_SyncTicks".
I am no expert, but I read that SDL_Delay() is a way to release the CPU to the scheduler. I tried to weave this into the culprit function, whilst trying to avoid it causing undesired lag. Like below. This does seem to do the trick, as total CPU usage is now around 7%. I added the +0.1 there as a hackish way to prevent the Framerate indicator dropping from 30 to the occasional 29 FPS. 

s_clock.c:
```
int32_t S_Clock_SyncTicks(int32_t target)
{
    double elapsed = 0.0;
    Uint64 last_ticks = m_Ticks;
    do {
        m_UpdateTicks();
        elapsed = (double)(m_Ticks - last_ticks) / m_Frequency;
        if ((elapsed +0.1) < (double)target) SDL_Delay(1); // NEW LINE ADDED
    } while (elapsed < (double)target);
    return elapsed;
}
```

**Comment by walkawayy** [comment]
https://gamedev.stackexchange.com/questions/129269/game-loop-getting-58-62-fps-why-not-exactly-60fps-sdl-c-osx

This suggests adding delay could result in the game missing its necessary wakeup time? Gonna tag @rr- for this.

**Comment by oziphantom** [comment]
well yes, I have a patch that uses this as "the way to fix potato performance" just not been able to get somebody with said potato to actually test it, or had the time to power up one of my old machines that might just be potato enough to actually work as a solid test. 

This will drop the games CPU from 100% to 1.2% on my machine ( but I have a 20 core 12th gen i7 so not a real world test). The cost however is that sleep function is wildly inaccurate  and will waver around a lot and its accuracy depends on the machine in question, i.e on a 20 core win11 it should be pretty accurate as there are lots of core it can schedule the code to run on and not have to fight anything. On a 1 core winXP your dreaming, you will ask for 12 and get given 11,22,17,29,6,13 and like it. I did notice even on my machine that the frame timings were "not linear".  
The issues with 30fps is that 29fps is 34.48ms and 31fps is 32.25ms so depending on how the fps is rounding you still have up to 1~2ms delta that will still count as "30fps" not a big deal but if it waivers a lot you will _feel_ it.

If the test was successful on the "potato" then my proposed optional solution ( i.e we would use super accurate by default and then have an enable_alternative_timing_hybrid (for lower performance) and then a enable_alternative_timing_loose(for really low performance) in the config ) would be to do some form of Runge–Kutta measure approach to work out what time we can request to get 90% mostly of the free time period and then look into the original accurate loop to bring us up to the mark. Aka the "saw and sand to the line" technique. Given (my 60fps version not withstanding) we have 33.33ms per frame which give us lots of head room as the logic of this game will run in a P90 frame just fine we should not be taking much CPU at all (there are other issues with the modern GPU usage so that is another kettle of fish that cause it to go a lot higher than one would expect) so even if we ask for sleep(16.66f) and it actually goes wildly over and takes 25, we are still well within tolerance. 

My theory and hope is that by giving the host OS a solid "now you can have the CPU again" at the convenient time will then allow it to schedule and handle other system tasks with minimal impact to our games flow, so even if we just do sdl_delay(1) and then measure to the line, the 1 will go way over but that is fine, it will stop the OS from fighting with us and then taking over for longer periods after it stops us at the wrong moment. Or maybe just doing 16 and call it a day will be good enough and avoid the whole measure and adjust logic ;) 

if you are willing to test such a theory could you please report back on the performance outcome with 
```
int32_t S_Clock_SyncTicks(int32_t target)
{
    double elapsed = 0.0;
    Uint64 last_ticks = m_Ticks;
    SDL_Delay(1); // NEW LINE ADDED
    do {
        m_UpdateTicks();
        elapsed = (double)(m_Ticks - last_ticks) / m_Frequency;
    } while (elapsed < (double)target);
    return elapsed;
}
```
and see if that will give you decent in game performance still, even disable the FBO renderer and crank it back up to full screen as it was before the latest release.

**Comment by Gerwin2k** [comment]
> well yes, I have a patch that uses this as "the way to fix potato performance" just not been able to get somebody with said potato to actually test it, or had the time to power up one of my old machines that might just be potato enough to actually work as a solid test.

I appreciate the intention. Yet I suppose it is desirable to separate performance on older/slower hardware from the CPU release subject.  Instead putting that performance subject in another ticket. (Yes I do have a suitable potato system (AMD E-350), but that one wastes much less time in S_Clock_SyncTicks. On that one the GL rendering + animation functions are topmost in the profiler list, regardless of whether or not SDL_Delay is implemented. My SDL_Delay implementation does not take away FPS performance on that potato system, it does not really improve FPS there either, and that is what I would expect)

Your S_Clock_SyncTicks is actually very similar to my version. But yours always does the SDL_Delay, even when the circumstances would make the game want to leave this function and loop immediately, when time is lacking. In my version I tried to make it so that the SDL_Delay is only done when there is indication that there is time to spare. 

@walkawayy
Thanks for the reference. I will read it better later.

**Comment by oziphantom** [comment]
well to me the main purpose of such a change would be to help support older/slower hardware performance. I.e if your machine can handle the current system you would choose it as the other system is not reliable. The only reason to adopt it is to improve performance. 
Where improve is defined as "make nicer" rather than "higher fps" per se. 
i.e while it might not push the FPS up, given the system a known convenient time and some form of amount to gauge it being able to handle other threads/interrupts/tasks etc lets it smooth those tasks out and thus doesn't force a take over at an inconvenient time. Perhaps giving a smoother frame rate rather than a faster one.  (my change was to test such a scenario, i.e what happens if we give the OS a chance every frame?) 

Another case might be where having 1 core go 100% gives odd temperature readings or you are in a thermally constrained environment/inadequate cooling where having the system run so hard causes throttling of some form which in turn lowers clock speeds and hence gives you a lower FPS.

Or even just as a Battery saving option while taking a hit to frame rate or frame rate smoothness as a choice to prolong battery life.

**Comment by Gerwin2k** [comment]
These things you mention are the actual results of releasing the CPU. Potential benefits. 

It does not change the fact that somehow the drawing of the polygons is demanding in this engine. I would think the polycount is low, it looks low, like it was in 1996. Suggesting an AMD E-350 APU should be able to handle it easily. But at maximum it does 1440x1080 30fps, and only when bilinear filtering is disabled. 
You write "well to me the main purpose of such a change would be to help support older/slower hardware performance". CPU idling does not solve that, it maybe helps a little bit. But to solve it, one has to focus on the OpenGL implementation, which is beyond my programming experience. And beyond this ticket.

**Comment by Gerwin2k** [comment]
PS. Since I think the proposed CPU release is better then nothing, I updated the binary on my repository to include this method. 
http://gb-homepage.nl/download/backports/Tomb1Main-2153-XPmod.zip

So far I did not find a cross-platform alternative to SDL_Delay().
Several tutorials implement SDL_Delay() in their gameloop. Some of these examples calculate (estimate) beforehand what amount of time they can yield to the scheduler, and pass that as a parameter. 
I don't know how times have changed, but I remember when programming with Allegro 4 for a Windows 98 game, that I had to add CPU idling in the loop. Meaning that old OS had a scheduler that could deal with it.
